name: Run pytest on Python program with artefacts

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r req.txt
    - name: Run Factorial program
      run: python factorial.py
    - name: Run pytest
      run: pytest test.py
    - name: Run pytest_new 
      run: pytest test.py --junitxml=junit/test-results.xml --cov=.
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: junit/test-results.xml
    - name: Generate coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/
