name: Run custom Docker container from Docker Hub

on: [push, pull_request]

env:
  DOCKERHUB_USERNAME: 'psrv3'
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Pull Docker image
        run: docker psrv3/newfa

      - name: Run Docker container
        run: docker run -it -p 5001:5001 psrv3/newfa
