name: Run Docker container from Docker Hub

on: [push, pull_request]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

#       - name: Pull Docker image
#         run: docker pull <your-dockerhub-username>/<your-docker-image-name>:<your-docker-image-tag>

      - name: Run Docker container
        run: docker run hello-world
      - name: Push to docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: psrv3/devopswithpy111
          tag_with_ref: true
