name: Run custom Docker container from Docker Hub

on: [push, pull_request]

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull psrv3/newfa

      - name: Run Docker container
        run: docker run -d -p 5001:5001 --name mycontainer psrv3/newfa
     
      - name: Sleep for 100 seconds
        run: sleep 100s
        shell: bash
        
      - name: Check Docker logs
        run: docker logs mycontainer > logs.txt
        
      - name: Cat log file
        run: cat logs.txt
